package org.grayleaves.utility;

public enum ParameterSpaceMapperEnum
{
	COMPARED_MATCHES_BASELINE, 
	COMPARED_PARTIALLY_OVERLAPS_BASELINE, 
	COMPARED_IS_SUBSET_OF_BASELINE,
	BASELINE_IS_SUBSET_OF_COMPARED,
	COMPARED_IS_DISJOINT_WITH_BASELINE

}
